; Script generated by the Antigravity AI assistant.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Language Layout OSD"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "mp"
#define MyAppExeName "LanguageLayoutOsd.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside Inno Setup IDE.)
AppId={{5F7BD623-1498-4D4F-94B6-613CCBE8C63E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\Programs\LanguageLayoutOsd
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=..\..\LICENSE
OutputDir=..\..\dist
OutputBaseFilename=LanguageLayoutOsd-Setup
SetupIconFile=..\..\tray.ico
Compression=lzma
SolidCompression=yes
; "PrivilegesRequired=lowest" instructs Setup to run as a non-administrative user
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\bin\Release\net45\LanguageLayoutOsd.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\net45\LanguageLayoutOsd.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\net45\tray.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\bin\Release\net45\osd-config.sample.json"; DestDir: "{app}"; Flags: ignoreversion
; Copy sample as the live config only if the live config does not already exist
Source: "..\..\bin\Release\net45\osd-config.sample.json"; DestName: "osd-config.json"; DestDir: "{app}"; Flags: onlyifdoesntexist

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
